import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import File1 from './File1'
import File2 from './file2'
import Try from './Try'
import Todolist from './Todolist'
import ModalTodo from './Modal'
import Display from './Display'
import React from 'react'
import axios from 'axios'
import DummyCal from './DummyCal'
import DummyCal2 from './DummyCal2'
import DummyCal3 from './DummyCal3'
import DummyTask1 from './DummyTask1'

export default function Home() {




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*
      <File2  /> 
      <DummyCal />
       <DummyCal2/>
    <DummyCal3 />

      */

      }
      <DummyTask1 />
    
    </div>

  )
}

export async function GetCalendarEvents(id) {
  const _id = "63ac28cbf8f9aa38a853831b"
  return await (await axios.get(`http://localhost:4000/projects/SingleProject/${_id}`)).data[0].calendar
}